### PR TITLE
tracer: add a binary search script

### PR DESCRIPTION
**Pull request by gusiri**
This PR adds a debugging script for `linea_generateConflatedTracesToFileV2`. 
One can use this binary search script to find out the exact block with an error. 

It binary-searches the full range. When the range has no errors, it will skip the range. 

Usage: 
`./binary_search.sh 4315801 4315832`

Result: `binary_search_4315801_4315832.log`
You can easily see that the block `4315803` has an isssue. 

```
Testing range: 4315801 - 4315832
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}

Testing range: 4315801 - 4315816
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}

Testing range: 4315801 - 4315808
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}

Testing range: 4315801 - 4315804
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}

Testing range: 4315801 - 4315802
{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"0.5.1-beta","conflatedTracesFileName":"/data/besu/conflated/4315801-4315802.conflated.0.5.1-beta.lt"}}
Range 4315801 - 4315802 is successful, skipping further investigation in this range.

Testing range: 4315803 - 4315804
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}

Testing block: 4315803
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Plugin internal error","data":"Exceptions triggered while tracing:\n  - class org.apache.tuweni.bytes.MutableArrayWrappingBytes cannot be cast to class org.apache.tuweni.bytes.Bytes32 (org.apache.tuweni.bytes.MutableArrayWrappingBytes and org.apache.tuweni.bytes.Bytes32 are in unnamed module of loader 'app')\n"}}

Testing block: 4315804
{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"0.5.1-beta","conflatedTracesFileName":"/data/besu/conflated/4315804-4315804.conflated.0.5.1-beta.lt"}}
Range 4315804 - 4315804 is successful, skipping further investigation in this range.

Testing range: 4315805 - 4315808
{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"0.5.1-beta","conflatedTracesFileName":"/data/besu/conflated/4315805-4315808.conflated.0.5.1-beta.lt"}}
Range 4315805 - 4315808 is successful, skipping further investigation in this range.

Testing range: 4315809 - 4315816
{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"0.5.1-beta","conflatedTracesFileName":"/data/besu/conflated/4315809-4315816.conflated.0.5.1-beta.lt"}}
Range 4315809 - 4315816 is successful, skipping further investigation in this range.

Testing range: 4315817 - 4315832
{"jsonrpc":"2.0","id":1,"result":{"tracesEngineVersion":"0.5.1-beta","conflatedTracesFileName":"/data/besu/conflated/4315817-4315832.conflated.0.5.1-beta.lt"}}
Range 4315817 - 4315832 is successful, skipping further investigation in this range.
[ec2-user@ip-172-31-6-148 integration_test]$ 
```

### CODE REVIEW

**Comment by letypequividelespoubelles** [comment]
Could you add a search for the failing tx in the block ? 

And then a script that extract the failing tx so that we keep only this in the replay tests ? (When it makes sense of course, sometimes we need the full block / conflation).

**Comment by gusiri** [comment]
@letypequividelespoubelles 
Sure, I can do it, but I need more knowledge on it.

1. What is the best way to find the failing transaction in a block?
2. How do you extract the failing transaction and build a replay file from it? Is it sufficient to remove the other transactions from the replay file?

**Comment by letypequividelespoubelles** [comment]
>     1. What is the best way to find the failing transaction in a block?

Once you found the failing block via you're script, do a binary search for txs in this blocks. Imho, it's enough to delete half txs in json file
 
>     2. How do you extract the failing transaction and build a replay file from it? Is it sufficient to remove the other transactions from the replay file?

for me yes, it's enough to remove all other txs.

@DavePearce would have a better insight. I'm wondering if we might break things while doing so, as the same sender can send several txs in the same block ...

**Comment by OlivierBBB** [comment]
> it's enough to remove all other txs.

That may not always work (e.g. there are several transactions with the same sender, one of which causes a problem, then you can't remove the first transactions or tests will fail because of the nonce.)

I think going to the level of the block is sufficient. Going to transactions will cause problems.

**Pull request merged**
