### PR TITLE
feat: update gradle test config to show better output

### LINKED ISSUE #1020: Improve output for `go-corset` in Github Action
The output we're getting from `go-corset` is not super helpful.  There are two aspects:

1. We're not seeing any `INFO` or `DEBUG` log information.  Whilst this matches what we get from Rust `corset`, I think we can do better.
2. We're not getting any logs being uploaded which can then be inspected.

### PR DESCRIPTION
**Pull request by DavePearce**
This updates the gradle test configuration to generate better output during testing.  In particular, so we can see why a particular test failed rather than just "FAILED".  This will be helpful for both Rust `corset` and `go-corset`.

### CODE REVIEW

**Comment by DavePearce** [comment]
I wonder if makes sense to flip this to `false` as well:

```java
    // set to false to hide passed standard out and error streams
    showPassedStandardStreams true
```

Since we only care about the output when the test fails?

**Review by letypequividelespoubelles — APPROVED** [review]
LGTM

**Comment by letypequividelespoubelles** [comment]
> I wonder if makes sense to flip this to `false` as well:
> 
> ```java
>     // set to false to hide passed standard out and error streams
>     showPassedStandardStreams true
> ```
> 
> Since we only care about the output when the test fails?

I do agree, it would be easier to read if we print only failing test

**Comment by DavePearce** [comment]
Ok, will put that in place and see how it looks.

**Pull request merged**
