### PR TITLE
[831] New ToyExecutionEnvironment that build the General State Test Case spec to run tests

### PR DESCRIPTION
**Pull request by gauravahuja**
I created a copy of GeneralStateTestCaseEipSpec from the besu repo and a copy of ToyExecutionEnvironment as ToyExecutionEnvironmentV2 for faster iteration.

ToyExecutionEnvironmentV2 is very similar to ToyExecutionEnvironment but builds the GeneralStateTestCaseEipSpec and has a method to execute the test using the spec.

#831

### CODE REVIEW

**Comment by FlorianHuc** [comment]
The approach looks good to me. Did you rewrite a unit test using ToyExecutionEnvironmentV2?

**Comment by gauravahuja** [comment]
> The approach looks good to me. Did you rewrite a unit test using ToyExecutionEnvironmentV2?

@FlorianHuc I updated the MXPTest to use the new approach.

**Review by FlorianHuc — APPROVED** [review]

**Review by powerslider — APPROVED** [review]

**Comment by OlivierBBB** [comment]
Have you tried tests to see if this fixes known issues @powerslider ?

**Comment by OlivierBBB** [comment]
@powerslider https://github.com/Consensys/linea-tracer/pull/842#issuecomment-2293668784

**Pull request merged**
