### PR TITLE
Validate tx max calldata

### PR DESCRIPTION
**Pull request by fab-10**
Move the validation of the calldata size of a transaction, from the Linea Besu fork, into the TransactionValidator plugin, plus some minor optimization and code reorgs

### CODE REVIEW

**Comment by macfarla** [comment]
There is an actual test failure I think
```

PluginTest > deniedTransactionNotAddedToTxPool() FAILED
    org.opentest4j.AssertionFailedError at PluginTest.java:238
```

**Comment by fab-10** [comment]
> There is an actual test failure I think
> 
> ```
> 
> PluginTest > deniedTransactionNotAddedToTxPool() FAILED
>     org.opentest4j.AssertionFailedError at PluginTest.java:238
> ```

Could not reproduce locally, created https://github.com/Consensys/besu-sequencer-plugins/pull/323 to have the test report

**Comment by fab-10** [comment]
@macfarla test fixed

**Comment by macfarla** [comment]
LGTM. the `tests` task is failing in CI because the ssh arg only works in this repo (not forks). You can push your branch directly to this repo and it will work

**Review by macfarla — APPROVED** [review]

**Comment by fab-10** [comment]
close here to recreate the same from a branch of the main repo

**Comment by fab-10** [comment]
@macfarla had to reopen a new one from a branch, please review #337

**Pull request closed without merging**
